import random
num = random . randint(1, 100)
print("Question: Try to  find the  number which has been generated by computer ;) It is between [1,100] range. Everytime you type the answer, which is upper or less then the generated one,the system will show you the appropriate message. Let's try :)")

guess =int(input("Enter an  integer:"))
num = 11

while guess > 11:
    print("Oops!!! try one more time;) Your  number  is  higher then mine")
    guess =int(input("Enter an  integer:"))
while guess < 11:
    print("Oops!!! try one more time;) Your  number  is  less then mine")
    guess =int(input("Enter an  integer:"))
if guess == 11:
    print("Woww!!! You guess it. Congrates")
    

